/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AppWatchlistRouteImport } from './routes/_app.watchlist'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRiskRouteImport } from './routes/_app.risk'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppJournalRouteImport } from './routes/_app.journal'
import { Route as AppImportRouteImport } from './routes/_app.import'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/import': typeof AppImportRoute
  '/journal': typeof AppJournalRoute
  '/profile': typeof AppProfileRoute
  '/risk': typeof AppRiskRoute
  '/settings': typeof AppSettingsRoute
  '/watchlist': typeof AppWatchlistRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/import': typeof AppImportRoute
  '/journal': typeof AppJournalRoute
  '/profile': typeof AppProfileRoute
  '/risk': typeof AppRiskRoute
  '/settings': typeof AppSettingsRoute
  '/watchlist': typeof AppWatchlistRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/import': typeof AppImportRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/risk': typeof AppRiskRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/watchlist': typeof AppWatchlistRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/calendar'
    | '/dashboard'
    | '/import'
    | '/journal'
    | '/profile'
    | '/risk'
    | '/settings'
    | '/watchlist'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/calendar'
    | '/dashboard'
    | '/import'
    | '/journal'
    | '/profile'
    | '/risk'
    | '/settings'
    | '/watchlist'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/analytics'
    | '/_app/calendar'
    | '/_app/dashboard'
    | '/_app/import'
    | '/_app/journal'
    | '/_app/profile'
    | '/_app/risk'
    | '/_app/settings'
    | '/_app/watchlist'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/watchlist': {
      id: '/_app/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk': {
      id: '/_app/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppImportRoute: typeof AppImportRoute
  AppJournalRoute: typeof AppJournalRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRiskRoute: typeof AppRiskRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppImportRoute: AppImportRoute,
  AppJournalRoute: AppJournalRoute,
  AppProfileRoute: AppProfileRoute,
  AppRiskRoute: AppRiskRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWatchlistRoute: AppWatchlistRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
